import argparse

from litestats import litestats

parser = argparse.ArgumentParser()
parser.add_argument(
    'statsfile',
    help='The statsfile generated by cProfile',
)


def main():
    args = parser.parse_args()
    statsfile = args.statsfile

    outfile = statsfile + '.sqlite3'
    litestats.main(statsfile, outfile)


if __name__ == '__main__':
    main()
